language: node_js
node_js: lts/*
deploy:
    provider: npm
    email: akanshul97@gmail.com
    api_key:
        secure: StSdMtlRVyJgmy1QytusYjJ4MlPrxMMvqL4J1cfBYA0LJOT8OXkPiuWusjOq9NlFo8ITZR/ihZcEUoVAeuqfwc4vtXaa1ALdF3TfFfXmE/mRKEff5sinZ7NcznU8qiSmIAlGk1zysls9jhuUEAtKzyg+J1VZ+vS7gMpgC6Ju9wDuSnpRqP/bYxohPEqzBIK5zs8szArkG3xmYHsT4MjyhCJ9msdsxhC95X+W6ESX35Mxvx9qY3waYxkYeIfi2irjLKK2PMnZkID1fBFfo/BpomKVM6DRsES7BTn7n1EIWFjQcFYrhK2DWRn5bqnCKq7yCruoXEzUGJ4lry35ZHzHrjfXKggab9ni04EKqh4ZGbwmLH/aAFYI3aknIv6JYnStSy6NKWaRafmC5jQ3V29limkCFb72h+nLoi+/aVhyBnLr3AC0SpezQ227U7HV2T1M7zy5Kdxw95eM6ruNCw31yTWhQ7ypbfYKbZk7+OEzA2lDZBEOSqfhn/Yc9Qp0PvqCdU1/dD9l31g0Ql/0VAgxbuwaWEZ+FDlRyXkxaCAzdECeRuMlKw3/+1S8FJ63j31t7p87plK2b8jPug9uzsRaEOaMZxBqMIuMKXyNfTno8tfDBD3eZ1HmOB3fCp7UN+oNug5PWJHrolomlmaLB49axeZASdLNoLQUvgdPZpMhSRI=
    on:
        repo: andydevs/servekaro
skip_cleanup: true
